version: '3.3'

services:
  db:
    container_name: db-mysql
    image: mysql:5.6.47
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: go-bookstore
